# Generated by Django 5.0.3 on 2024-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('designation', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('team', models.CharField(blank=True, choices=[('Data_Analyst', 'Data_Analyst'), ('Dev_Ops', 'Dev_Ops'), ('Backend', 'Backend'), ('sales', 'Sales'), ('Frontend', 'Frontend')], max_length=20, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('password', models.CharField(default='', max_length=255)),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompleted',
            fields=[
                ('tcid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('task_completed_id', models.CharField(max_length=20, unique=True)),
                ('task_id', models.CharField(max_length=20)),
                ('employee_id', models.CharField(max_length=20)),
                ('manager_id', models.CharField(max_length=20)),
                ('completed_date', models.DateTimeField()),
                ('remark', models.TextField()),
                ('percentage_done', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hours_contributed', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRejected',
            fields=[
                ('trcid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('task_rejected_id', models.CharField(max_length=20, unique=True)),
                ('task_id', models.CharField(max_length=20)),
                ('employee_id', models.CharField(max_length=20)),
                ('manager_id', models.CharField(max_length=20)),
                ('rejected_date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('hours_contributed', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('manager_id', models.CharField(max_length=20)),
                ('employees', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('percentage_Completed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.CharField(max_length=20, null=True)),
                ('team', models.CharField(blank=True, choices=[('Data_Analyst', 'Data_Analyst'), ('Dev_Ops', 'Dev_Ops'), ('Backend', 'Backend'), ('sales', 'Sales'), ('Frontend', 'Frontend')], max_length=20, null=True)),
            ],
        ),
    ]
