# Generated by Django 5.0.3 on 2024-03-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('manager_id', models.CharField(max_length=20)),
                ('employees', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('percentage_Completed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.CharField(max_length=20, null=True)),
                ('team', models.CharField(blank=True, choices=[('Data_Analyst', 'Data_Analyst'), ('Dev_Ops', 'Dev_Ops'), ('Backend', 'Backend'), ('sales', 'Sales'), ('Frontend', 'Frontend')], max_length=20, null=True)),
            ],
        ),
    ]
