# Generated by Django 5.0.3 on 2024-03-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
