# Generated by Django 4.1.5 on 2024-03-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_task_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=20)),
                ('task_id', models.CharField(max_length=20)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completed_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
