# Generated by Django 4.1.5 on 2024-03-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='hours',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hours',
            name='team',
            field=models.CharField(blank=True, choices=[('Data_Analyst', 'Data_Analyst'), ('Dev_Ops', 'Dev_Ops'), ('Backend', 'Backend'), ('sales', 'Sales'), ('Frontend', 'Frontend')], max_length=20, null=True),
        ),
    ]
